CREATE DATABASE EminERP_DB;
GO

USE EminERP_DB;
GO

CREATE TABLE Users (
    Id INT PRIMARY KEY IDENTITY(1,1),
    Username NVARCHAR(50) UNIQUE NOT NULL,
    Password NVARCHAR(250) NOT NULL,
    Role NVARCHAR(20) DEFAULT 'Staff'
);
GO

INSERT INTO Users (Username, Password, Role) 
VALUES ('admin', '123456', 'Admin');
GO